package ro.teamnet.neo.plugin;

public enum  Neo4JType {

    DEFAULT_NEO_4J_CONFIGURATION,
    NEO_4J_CONFIGURATION,
    PACKAGE_TO_SCAN,
    DEFAULT_RESOURCE_PROPERTIES_PATH,
    RESOURCE_PROPERTIES_PATH
    ;
}
